services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGO_URL=${MONGO_URL}
      - DB_NAME=${DB_NAME}
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - .:/app
    command: node server.js

  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db


volumes:
  mongo_data:
