services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_URL=mongodb://mongo:27017/interbanking
      - DB_NAME=interbanking
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: node server.js

  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db


volumes:
  mongo_data:
