services:
  interbanking:
    build: .
    ports:
      - "4000:8080"
    environment:
      - PORT=8080
      - MONGO_URL=${MONGO_URL}
      - DB_NAME=${DB_NAME}
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - .:/interbanking
    command: node server.js

  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/interbanking